DECENTfoundation/dcorejs

- src/examples/Transfer/transfer.html
- src/examples/Transfer/transfer.js
https://decentplatform.atlassian.net/browse/DGO2-226
> [+] transfer example created

- package-lock.json
- package.json
https://decentplatform.atlassian.net/browse/DGO2-228
> Pre-push hook, tests separation

- package-lock.json
- package.json
[-] remove unused phantomjs dependency
[*] prepublish replaced by prepublishOnly due to deprication
> [*] prepublish replaced by prepublishOnly due to deprication

- src/crypt.ts
- src/test/client/unit/crypt.test.js
- src/test/server/unit/crypt.test.ts
https://decentplatform.atlassian.net/browse/DGO2-238
> [+] encrypt/decrypt with password added, tests

- README.md
https://decentplatform.atlassian.net/browse/DJS-4
> [+] browser support, server and browser initialization separated

- src/api/database.ts
- src/content.ts
https://decentplatform.atlassian.net/browse/DJS-3
> [+] getRating method added

- README.md
- src/api/database.ts
- src/explorer.ts
https://decentplatform.atlassian.net/browse/DJS-16
> [+] getMiner, getMiners, listMiners methods added

- src/explorer.ts
https://decentplatform.atlassian.net/browse/DJS-20
> [*] fixed inconsistent parameter type

- src/test/client/declarations.js
- src/test/client/integration/account.test.js
- src/test/client/integration/content.test.js
- src/test/server/integration/account.test.ts
- src/test/server/integration/content.test.ts
https://decentplatform.atlassian.net/browse/DJS-21
> [*] integ test data fix

- src/api/apiConnector.ts
Fixed issue with tsc build (Parameter 'ConnectionState' implicitly has an 'any' type.)
> Tsc building issue

- src/examples/SubmitContent/submitContent.js
- src/model/content.ts
- src/modules/content.ts
- src/utils.ts
https://decentplatform.atlassian.net/browse/DJS-9
> Djs 9 transfer uia support

- src/model/account.ts
https://decentplatform.atlassian.net/browse/DJS-36
> Fix DJS-36 DCT transfer amount calculation fix

- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-38
> Update DJS-38 remove brainkey from exportWallet method

- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-39
> Update DJS-39 parameter fromId added to getAccountHistory method

- src/model/account.ts
https://decentplatform.atlassian.net/browse/DJS-41
> Update DJS-41 History record op parameter type changed to any

- src/model/account.ts
- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-41
> Djs 41 wallet suppot

- src/model/content.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-34
> Djs 34 content uia support

- src/modules/asset.ts
https://decentplatform.atlassian.net/browse/DJS-23
> Djs 35 asset module uia support

- src/model/mining.ts
- src/model/transaction.ts
- src/modules/mining.ts
https://decentplatform.atlassian.net/browse/DJS-28
> Djs 28 mining module

- src/api/model/database.ts
- src/dcore.ts
- src/model/proposal.ts
- src/model/transaction.ts
- src/modules/proposal.ts
- src/transaction.ts
https://decentplatform.atlassian.net/browse/DJS-44
> Djs 44 proposal module

- src/modules/account.ts
- src/utils.ts
- account history options fix
- asset amount formatting - in case of 0.00001 amount bad formatting
> Quick fixes

- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-25
> Add DJS-46 content generate encryption key method

- src/modules/account.ts
- src/modules/asset.ts
- src/modules/content.ts
- src/modules/mining.ts
- src/modules/proposal.ts
- src/transaction.ts
https://decentplatform.atlassian.net/browse/DJS-48
> Add DJS-48 transaction builder methods

- src/dcore.ts
- src/transaction.ts
https://decentplatform.atlassian.net/browse/DJS-48
> Add DJS-48 get prototype operation method

- src/model/content.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-51
> Fix DJS-51 asset formatting fix

- src/api/chain.ts
- src/api/model/chain.ts
- src/dcore.ts
- src/modules/account.ts
- src/modules/asset.ts
- src/modules/content.ts
- src/modules/mining.ts
- src/modules/proposal.ts
https://decentplatform.atlassian.net/browse/DJS-47
> Djs 47 chainapi refactor

- package-lock.json
- package.json
- src/api/apiConnector.ts
https://decentplatform.atlassian.net/browse/DWVA-136
> Dwva 136 socket fallback

- README.md
- src/api/messaging.ts
- src/api/model/messaging.ts
- src/dcore.ts
- src/model/messaging.ts
- src/model/transaction.ts
- src/modules/messaging.ts
- src/utils.ts
https://decentplatform.atlassian.net/browse/DJS-26
> Djs 26 messaging module

- src/model/mining.ts
- src/modules/mining.ts
https://decentplatform.atlassian.net/browse/DJS-54
> Feat DJS-54 listMiners and getMiner methods added

- src/dcore.ts
- src/modules/ApiModule.ts
- src/modules/account.ts
- src/modules/asset.ts
- src/modules/content.ts
- src/modules/explorer.ts
- src/modules/messaging.ts
- src/modules/mining.ts
- src/modules/proposal.ts
- src/modules/seeding.ts
- src/modules/subscription.ts
- src/publicApi.ts
https://decentplatform.atlassian.net/browse/DJS-55
> Djs 55 api module refactor

- src/dcore.ts
- src/model/account.ts
- src/model/content.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-61
> Djs 61 co authors type fix

- src/model/asset.ts
- src/modules/asset.ts
https://decentplatform.atlassian.net/browse/DJS-70
> Feat DJS-70 RealSupply model added

- src/api/apiConnector.ts
- src/dcore.ts
https://decentplatform.atlassian.net/browse/DJS-75
> Feat DJS-75 openConnection, closeConnection added

- src/transactionBuilder.ts
https://decentplatform.atlassian.net/browse/DJS-67
> Add DJS-67 remove public key parameter from sign transaction

- src/api/model/chain.ts
https://decentplatform.atlassian.net/browse/DJS-57
> Defined DJS-57 subscription data type

- src/model/content.ts
- src/model/transaction.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-72
> Update DJS-72 content

- src/dcore.ts
https://decentplatform.atlassian.net/browse/DJS-83
> Djs 83 remove init reference

- README.md
https://decentplatform.atlassian.net/browse/DJS-82
> Docs DJS-82 create account section added to README

- src/model/explorer.ts
- src/modules/explorer.ts
https://decentplatform.atlassian.net/browse/DJS-56
> Djs 56 explorer modul refactor

- src/modules/explorer.ts
https://decentplatform.atlassian.net/browse/DJS-85
> Refactor DJS-85 explorer method

- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-86
> Djs 86 content ratings

- src/modules/mining.ts
https://decentplatform.atlassian.net/browse/DJS-89
> Fix DJS-89 unvote last miner fix

- src/modules/mining.ts
https://decentplatform.atlassian.net/browse/DJS-89
> Fix DJS-89 unvote miner fix

- README.md
https://decentplatform.atlassian.net/browse/DJS-87
> Docs DJS-87 submitContent added to readme

- src/model/content.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-88
> Feat DJS-88 addContent params type check

- README.md
https://decentplatform.atlassian.net/browse/DJS-91
> Updated DJS-91 bad example

- README.md
https://decentplatform.atlassian.net/browse/DJS-87
> Docs DJS-87 submit content README update

- README.md
https://decentplatform.atlassian.net/browse/DJS-90
> Djs 90 readme update

- src/model/account.ts
- src/modules/ApiModule.ts
- src/modules/account.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-94
> Djs 94 account module typecheck

- src/model/proposal.ts
- src/modules/account.ts
- src/modules/proposal.ts
https://decentplatform.atlassian.net/browse/DJS-100
> Added DJS-100 type check for proposal module

- src/model/asset.ts
- src/model/types.ts
- src/modules/ApiModule.ts
- src/modules/BaseObject.ts
- src/modules/asset.ts
https://decentplatform.atlassian.net/browse/DJS-95
> Djs 95 asset module typechekc

- src/model/seeding.ts
- src/modules/seeding.ts
https://decentplatform.atlassian.net/browse/DJS-101
> Updated DJS-101 type check for seeding module

- src/model/messaging.ts
- src/modules/messaging.ts
https://decentplatform.atlassian.net/browse/DJS-98
> Updated DJS-98 type check for messaging module

- src/api/model/database.ts
- src/modules/BaseObject.ts
- src/modules/content.ts
https://decentplatform.atlassian.net/browse/DJS-96
> Djs 96 content module typecheck

- src/model/mining.ts
- src/modules/mining.ts
https://decentplatform.atlassian.net/browse/DJS-99
> Djs 99 mining module typecheck

- src/model/proposal.ts
- src/modules/asset.ts
- src/modules/messaging.ts
- src/modules/proposal.ts
- src/modules/seeding.ts
- src/modules/subscription.ts
- src/transactionBuilder.ts
https://decentplatform.atlassian.net/browse/DJS-105
> Djs 105 transaction builder type check

- src/crypt.ts
https://decentplatform.atlassian.net/browse/DJS-103
> Add DJS-103 type check for crypto utils

- src/model/transaction.ts
- src/modules/account.ts
- src/modules/validator.ts
- src/transactionBuilder.ts
- src/utils.ts
https://decentplatform.atlassian.net/browse/DJS-106
> Handle DJS-106 rejected wrong error

- src/crypt.ts
- src/model/account.ts
- src/model/operationPrototype.ts
- src/model/transaction.ts
- src/modules/account.ts
- src/modules/asset.ts
- src/modules/messaging.ts
- src/modules/proposal.ts
- src/test/client/unit/crypt.test.js
- src/test/server/unit/crypt.test.ts
- src/utils.ts
https://decentplatform.atlassian.net/browse/DJS-107
> Djs 107 crypto utils refactor

- src/model/account.ts
- src/model/transaction.ts
- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-111
> Refactor DJS-111 acccountUpdate optional params

- src/modules/messaging.ts
https://decentplatform.atlassian.net/browse/DJS-109
> Refactor DJS-109 send message return type refac

- src/api/chain.ts
- src/api/model/chain.ts
- src/dcore.ts
https://decentplatform.atlassian.net/browse/DJS-110
> Refactor DJS-110 subscription mechanism refactor

- src/modules/ApiModule.ts
- src/modules/account.ts
- src/modules/asset.ts
- src/modules/content.ts
- src/modules/messaging.ts
- src/modules/mining.ts
- src/modules/proposal.ts
- src/modules/subscription.ts
- src/transactionBuilder.ts
https://decentplatform.atlassian.net/browse/DJS-112
> Djs 112 set transaction fees

- src/api/apiConnector.ts
https://decentplatform.atlassian.net/browse/DJS-113
> Fix DJS-113 connection test not removing failed addresses

- src/model/transaction.ts
https://decentplatform.atlassian.net/browse/DJS-116
> Fix DJS-116 ContentObject id property added

- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-118
> Fix DJS-118 balance formatting fix

- src/dcore.ts
https://decentplatform.atlassian.net/browse/DJS-110
> Djs 110 subscription

- src/model/transaction.ts
https://decentplatform.atlassian.net/browse/DW-311
> Chore DW-311 UIA precision operation support added

- src/modules/account.ts
https://decentplatform.atlassian.net/browse/DJS-117
> Fix DJS-117 support transfer to name

- src/modules/content.ts
Content never dies, but can be **stringified**
> Fix variable name in content module
